journaux/urls.py
from django.urls import path
# from .views import listeJournaux
from .views import HomePageView

# urlpatterns = [
#     path("", listeJournaux, name="home"),
# ]
urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
]

sprint4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("journaux.urls")),
]

journaux/models.py
# journaux/models.py
from django.db import models

# class Journal(models.Model):
#     nom = models.CharField(max_length=100)
#     editeur = models.CharField(max_length=42)
#     description = models.TextField(null=True)
#     dateparution = models.DateTimeField(
#         auto_now_add=True, 
#         auto_now=False,
#         verbose_name="Date de parution"
#     )

#     def __str__(self):
#         """
#         Cette méthode que nous définirons dans tous les modèles
#         nous permettra de reconnaître facilement les différents objets que
#         nous traiterons plus tard et dans l'administration
#         """
#         return self.nom
from django.core.validators import MaxValueValidator, MinValueValidator
class Journal(models.Model):
	class Genre(models.TextChoices):
		MANAGEMENT = 'MAN'
		HIGH_TECH = 'IT'
		CUISINE = 'CUI'
		
	nom = models.CharField(max_length=100)
	genre = models.fields.CharField(choices=Genre.choices, max_length=5)
	editeur = models.CharField(max_length=42)
	description = models.TextField(null=True)
	dispo = models.fields.BooleanField(default=True)
	webpage = models.fields.URLField(null=True, blank=True)
	dateparution = models.DateTimeField(
        auto_now_add=True, 
        auto_now=False,
        verbose_name="Date de parution"
    )
    
	year_created = models.fields.IntegerField(
    validators=[MinValueValidator(1900), MaxValueValidator(2021)]
    )
    
	def __str__(self):
		return self.nom[:50]



class Article(models.Model):
	titre = models.CharField(max_length=100)
	auteur = models.CharField(max_length=42)
	nbpages = models.IntegerField()
	
	# Clé étrangère
	journal = models.ForeignKey(Journal, null=True, on_delete=models.SET_NULL)

	def __str__(self):
		return self.titre[:50]


class Categorie(models.Model):
	nom = models.CharField(max_length=100)
	
	def __str__(self):
		return self.nom[:50]
	
class Livre(models.Model):
	titre = models.CharField(max_length=100)
	auteur = models.CharField(max_length=42)
	date = models.DateTimeField(
        auto_now_add=True, 
        auto_now=False,
        verbose_name="Date de parution"
    )
	
	# Clé étrangère
	categorie = models.ForeignKey(Categorie, null=True, on_delete=models.SET_NULL)

	def __str__(self):
		return self.titre[:50]
	

journaux/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from journaux.models import Journal

# # Create your views here.
# def listeJournaux(request):
#     # Ramener tous les journaux
#     journaux = Journal.objects.all() 
    
#     # request, template, objet contextuel (le 1er élément)
#     # return render(request, "journaux/home.html", {"journaux":journaux[0]}
#     # )
    
#     page_num = request.GET.get('page', 1)
#     paginator = Paginator(journaux, 2) # 2 journaux per page


#     try:
#         page_obj = paginator.page(page_num)
#     except PageNotAnInteger:
#         # if page is not an integer, deliver the first page
#         page_obj = paginator.page(1)
#     except EmptyPage:
#         # if the page is out of range, deliver the last page
#         page_obj = paginator.page(paginator.num_pages)

#     # render(request, template, objet contextuel (tout))
#     # return render(request, "journaux/home.html", {"journaux":journaux}) 
#     return render(request, "journaux/home.html", {"page_obj":page_obj})

# Vue générique
from django.views.generic import ListView

class HomePageView(ListView):
	model = Journal
	context_object_name = 'page_obj'
	template_name = "journaux/home.html"


# PAGINATION AVEC UNE CLASSE
# from django.views.generic import ListView

# class HomePageView(ListView):
#     model = Journal
#     context_object_name = 'page_obj'
#     paginate_by = 1
#     template_name = "journaux/home.html"

journaux/templates/journaux/base.html
<!-- journaux/templates/journaux/base.html -->
<html>
    <head>
        <title>Les journaux</title>
    </head>
    <body>
        {% block content %}{% endblock content %}
    </body>
</html>

journaux/templates/journaux/home.html
<!-- journaux/templates/journaux/home.html -->
{% extends "journaux/base.html" %}

{% block title %}
{% endblock %}

{% block content %}
    <h1>Presse et mag</h1>
    <!-- <p>Nos {{ journaux|length }} magazines</p> -->

    <!-- affichage 1 par 1 -->
    <!-- <ul>
        <li>{{ journaux.0.nom}}</li>
        <li>{{ journaux.1.nom}}</li>
    </ul> -->

    <br>
    <!-- affichage for : VUE AVEC DEF-->
    <!-- <ul>
        {% for journal in journaux %}
        <li>{{ journal.nom}}</li>
        {% endfor %}
    </ul> -->

    <!-- affichage for : VUE AVEC CLASSE-->
    <!-- <ul>
        {% for journal in journal_list %}
        <li>{{ journal.nom}}</li>
        {% endfor %}
    </ul> -->

    <!-- Pagination -->
    <ul class="">
        {% for journal in page_obj %}
          <li>{{ journal.nom }}</li>
        {% endfor %}
    </ul>

    <br><hr>
    <li>{{ page_obj.1.nom}}</li>
     {% include "journaux/pagination.html" %}
{% endblock %}

journaux/templates/journaux/pagination.html
<div>
    <span>
      {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}
      <span>
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>
      {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">Next</a>
      {% endif %}
    </span>
  </div